# config/yaml/User.dcm.yml
Chat:
  type: entity
  table: chats
  id: { id: { type: integer, generator: {  strategy: AUTO } }}
  fields:
    topic:     { type: string }
  oneToMany:
    Users:
      targetEntity: User
      mappedBy: Chat
User:
  type: entity
  manyToOne:
    Chat:
      targetEntity: Chat
      inversedBy: Users