# config/yaml/Chat.dcm.yml
Chat:
  type: entity
  id: { id: { type: integer, generator: {  strategy: AUTO } }}
  fields:
    topic:     { type: string }
  oneToMany:
    Users:
      targetEntity: User
      mappedBy: Chat
    Log:
      targetEntity: Log
      mappedBy: Chat