# config/yaml/User.dcm.yml
User:
  type: entity
  table: users
  id: { id: { type: integer, generator: {  strategy: AUTO } }}
  fields:
    username: { type: string, length: 12 }
    password: { type: string, length: 100 }
    nick:     { type: string, length: 12 }

  manyToOne:
    Chat:
      targetEntity: Chat